//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Messages_Mapped
    {
        public int Users_Messages_MappedId { get; set; }
        public int MessageId { get; set; }
        public int UserId { get; set; }
        public int PlaceHolderId { get; set; }
        public bool IsRead { get; set; }
        public bool IsStarred { get; set; }
    
        public virtual Message Message { get; set; }
        public virtual MessagePlaceHolder MessagePlaceHolder { get; set; }
        public virtual User User { get; set; }
    }
}
